---
title: "Homework 2"
author: "Violetta Konygina"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
deck <- read.csv('~/deck.csv')
totalNumOfDecks <- 4
deck <- deck[rep(seq(nrow(deck)), totalNumOfDecks),]

head(deck)
```


## Dealer's hand
```{r}
dealer_hand <- data.frame(
  face = character(),
  suit = character(),
  value = numeric()
)
```

## Player's hand
```{r}
player_hand <- data.frame(
  face = character(),
  suit = character(),
  value = numeric()
)
```


##Shuffle deck function
```{r}
shuffle_deck <- function(deck){
  random <- sample(1:208, size = 208)
  deck <- deck[random, ]
}
```

##Start game function
```{r}
chances <- function(dealer_hand, player_hand, cur_deck){
    dealer_sum <- sum(dealer_hand$value)
    player_sum <- sum(player_hand$value)
    
    
    cat("Dealer's hand:", fill = T)
    print(dealer_hand, row.names = F)
    cat(c("sum", dealer_sum), fill = T)
    cat("Your hand:", fill = T)
    print(player_hand, row.names = F)
    cat(c("sum", player_sum,"\n"))
    
    
    if (dealer_sum <= player_sum && player_sum < 21) {
        cat("chances 100%")
        } 
    else if (player_sum > 21) {
        cat("chances 0%")
        } 
    else {
        max_lim <- 21 - player_sum
        min_lim <- dealer_sum - player_sum
        
        cards <- sum(cur_deck$value <= max_lim & cur_deck$value >= min_lim)
        cat('chances', round(cards/nrow(deck)*100), '%')
    }
    
  }


start_game <- function(dealer_hand, player_hand,cur_deck){
  
  cur_deck <- shuffle_deck(cur_deck)
  
  player_hand <<- cur_deck[1:2,]
  cur_deck <- cur_deck[-(1:2),]
  dealer_hand <<- cur_deck[1:2,]
  cur_deck <- cur_deck[-(1:2),]
  chances(dealer_hand, player_hand, cur_deck)
}


```

## Deal function
```{r}
deal <- function() {
  new_card <- cur_deck[1,]
  player_hand[nrow(player_hand) + 1,] <<- new_card
  cur_deck <<- cur_deck[-c(1), ]
  
  dealer_hand <<- dealer_hand

  chances(dealer_hand, player_hand, cur_deck)
}
```

## Stop game function
```{r}
stop_game<-function(player_hand, dealer_hand, cur_deck) {
  dealer_sum <- sum(dealer_hand$value)
  player_sum <- sum(player_hand$value)
  
  if (player_sum >= dealer_sum & player_sum <= 21) {
  cat("Result: Win")
  } 
  else {
  cat("Result: Loose")
  }
}
```


## Test 1
```{r}
cur_deck <- deck
start_game(dealer_hand, player_hand,deck)
```

```{r}
deal()
```

```{r}
stop_game(player_hand, dealer_hand, deck)
```

## Test 2

```{r}
start_game(player_hand, dealer_hand, deck)
```

```{r}
deal()
```

```{r}
stop_game(player_hand, dealer_hand, cur_deck)
```